### ISSUE TITLE
Add ability to ignore fields

### ISSUE THREAD

**Issue by abdulrahman1s** [kurtbuilds/ormlite#12]
`#[ormlite(skip)]` macro would be great!

**Comment by kurtbuilds** [comment]
I can imagine there’s use for this. The field would have to have a Default value, otherwise it couldn’t get populated. 

Can you motivate this with your use case?

**Comment by heroin-moose** [comment]
Having something in a struct that isn't stored in a database, for example. Like a runtime state.

**Comment by heroin-moose** [comment]
Or if you're building a composite object from different tables.

**Comment by kurtbuilds** [comment]
This is now implemented on master, will be cut on the next release.
