### ISSUE TITLE
How to express more WHERE clauses in a query

### ISSUE THREAD

**Issue by andreapavoni** [kurtbuilds/ormlite#18]
Hi there and thank you for this excellent library. I'm still very new to Rust and I've tried several approaches to interact with dbs (plain sqlx, diesel, SeaORM), but this one is very ergonomic and easy to use.

I've seen that with only 1 `WHERE` clause I can write something like:

```rust
Point::query("SELECT * FROM points WHERE x = ?")
        .bind(3i32)
        .fetch_all(&mut conn)
        .await?;
```

how can I express a query with 2 or more `WHERE` clauses, like this?

```sql
SELECT * from points WHERE x = 3 AND y = 10
```

thanks in advance!

**Comment by gmLucario** [comment]
Probably you can use another bind like `sqlx`

```
Point::query("SELECT * FROM points WHERE x = ? AND y = ?")
        .bind(3i32)
        .bind(8i32)
        .fetch_all(&mut conn)
        .await?;
```

**Comment by andreapavoni** [comment]
Yeah, I didn’t considered/tried the second bind. Thanks!

**Comment by kurtbuilds** [comment]
Feel free to submit a PR with a small update to the docs if you feel it'd be helpful!

I'll close this issue, as it appears resolved.
