### ISSUE TITLE
Map a custom struct while making join.

### ISSUE THREAD

**Issue by uwejan** [kurtbuilds/ormlite#24]
```
create table firms_users(
  firm_id integer references firms(id),
  user_id integer references users(id),
  primary key (firm_id, user_id)
);
```
How would I join on this table note the intended result would be some of users attributes + some of firm attributes not the whole model.
```
pub struct UserWithFirm {
    pub(crate) user: SlimUser,
    pub(crate) firm: SlimFirm,
}
```
Thank you.

**Comment by kurtbuilds** [comment]
Great question.

Right now there's only support for many-to-1 joins, though support for other types is planned.

If I'm understanding right, you're asking about a many-to-many join. You can work around the limitation mentioned by operating on the many to many table, rather than the User table or the Firm table. It looks something like this:

#[derive(Model)]
pub struct UserWithFirm {
    id: Uuid,
    user_id: Uuid,
    #[ormlite(many_to_one_key = user_id)]
    pub(crate) user: Join<SlimUser>,
    firm_id: Uuid,
    #[ormlite(many_to_one_key = firm_id)]
    pub(crate) firm: Join<SlimFirm>,
}

Once you have that struct, you should be able to apply select filters on the joined objects. Something like:

```rs
let results = UserWithFirm::select()
.join(UserWithFirm::organization())
.join(UserWithFirm::user())
.where_bind("user.active = ?", true)
.fetch_all(&pool)
.await?;

for uf in results {
    println!("user: {:?}", uf.user);
    println!("firm: {:?}", uf.firm);
}
```

**Comment by uwejan** [comment]
Thank you for taking a look into it.

Will the result be Vec, I noticed the loop. Well the intended result is only UserWithFirm struct, no Vec, becasue each user belongs only to one firm. Thus user: will be some of users attributes, firm: will be some of firms attributes.

**Comment by kurtbuilds** [comment]
Loop is because of the `fetch_all`. For one, try something like:

```rs
let uf = UserWithFirm::select()
.join(UserWithFirm::organization())
.join(UserWithFirm::user())
.where_bind("user.id= ?", 100)
.fetch_one(&pool)
.await?;


println!("user: {:?}", uf.user);
println!("firm: {:?}", uf.firm);
```

**Comment by uwejan** [comment]
Waht about runtime, I notice only `runtime-tokio-rustls` , Is there any plans for actix?

**Comment by kurtbuilds** [comment]
Actix runs on tokio. The runtime-actix is deprecated.

See this thread: https://www.reddit.com/r/rust/comments/qc3wc2/sqlx_exist_a_problem_if_pick_runtimeactix_vs/

**Comment by kurtbuilds** [comment]
This issue seems to be resolved. If there's a separate issue about the runtime options, let's put that in its own issue.
