### ISSUE TITLE
correct use of "one_to_many_foreign_key" ?

### ISSUE THREAD

**Issue by jackbackes** [kurtbuilds/ormlite#25]
https://github.com/kurtbuilds/ormlite/blob/f0be475f0ff688e406cac039942a14bb3960bdf1/attr/src/attr.rs#L79

How do I use this? Here is my example (using v0.14.2 with sqlite feature):

```
#[derive(Serialize, Deserialize, Debug, Clone, Model)]
pub struct Leg {
    #[ormlite(one_to_many_foreign_key = Execution::id)]
    executions: Join<Vec<Execution>>,
  ```

Error:

```
proc-macro derive panicked
message: not implemented
ormlite_macro
proc_macro Model
Derive macro for #[derive(Model)] It additionally generates FromRow for the struct, since Model requires FromRow.
```

**Comment by kurtbuilds** [comment]
It probably should be removed from the struct in master, but unfortunately one_to_many joins are not supported yet, only many_to_one / one_to_one. Apologies for getting your hopes up by having it defined in the struct.

**Comment by kurtbuilds** [comment]
To keep issues clean, I'm going to close this issue. The roadmap section is the best way to stay up to date on when this feature is completed.
