### ISSUE TITLE
[feature request] support count query & exists query

### ISSUE THREAD

**Issue by holmofy** [kurtbuilds/ormlite#35]
The current select query only supports querying all columns, which is very monotonous.

```rust
#[derive(Model, Debug)]
pub struct Person {
    pub id: i32,
    pub name: String,
    pub age: i32,
}

async fn query_builder_example() {
    let people = Person::select()
        .where_("age > ?")
        .bind(50i32)
        .fetch_all(&mut conn)
        .await?;
    println!("All people over 50: {:?}", people); 
}
```

It would be perfect if this library could provide `count` and `exists` APIs. count query and exists query are also very common query scenarios, it will be very convenient to build where clause through SelectQueryBuilder.

```rust
async fn query_builder_example() {
    let count = Person::count()
        .where_("age > ?")
        .bind(50i32)
        .fetch_all(&mut conn)
        .await?;

    let exists = Person::exists()
        .where_("age > ?")
        .bind(50i32)
        .fetch_all(&mut conn)
        .await?;
}
```

**Comment by kurtbuilds** [comment]
Why wouldn't you use raw queries for those?

You're not trying to ORM map an object when you do count(*) - you just need to map it to a number.

For exists, I think fetch_optional does the behavior you're describing. Or are you referring to SQL keyword EXISTS somehow?

**Comment by holmofy** [comment]
I'm new to rust and just started learning rust in the last few weeks. I found ormlite, an ORM library based on sqlx. I think ormlite is the best library I've found this week. Therefore, I hope it can provide more and better APIs so that more people can use and improve this library. I'm very sorry if these issues I raised have caused trouble to you. I will not raise any issues in the future.

**Comment by holmofy** [comment]
I'm new to rust and just started learning rust in the last few weeks. I found ormlite, an ORM library based on sqlx. I think ormlite is the best library I've found this week. Therefore, I hope it can provide more and better APIs so that more people can use and improve this library. I'm very sorry if these issues I raised have caused trouble to you. I will not raise any issues in the future.
