### ISSUE TITLE
document rustfmt options

### ISSUE THREAD

**Issue by nitn3lav** [kurtbuilds/ormlite#43]
The code doesn't seem to be formatted with the default [rustfmt config](https://rust-lang.github.io/rustfmt/). Because format on save is enabled in my editor, this means that large parts of the code are automatically reformatted. It would be nice if you could document which rustfmt options you use by adding a `rustfmt.toml`.

**Comment by kurtbuilds** [comment]
It's using IntelliJ formatting, which isn't deterministic.

You should be able to add an `rustfmt.tml` with `disable_all_formatting = true` to turn off your editor configuration. I'll happily accept that as a separate or part of a featureful PR
