### ISSUE TITLE
Usage with Mutex<SqliteConnection>

### ISSUE THREAD

**Issue by martpie** [kurtbuilds/ormlite#55]
First, thank you very much for this lib, it fits in a really neat spot between high-level without crazy concepts/boilerplayes and low-level possibilities.

I am working on porting my Tauri app to use SQLite as en embedded database. With Tauri, when the UI invoke a command, a thread is spawned in the rust process. There we can have access to some global state, typically, where someone would store the `SqLiteConnection` object.

This object must be wrapped in a Mutex, so it is thread-safe to access, as indicated in the doc: https://tauri.app/develop/state-management/#mutability

Now, trying to apply all that, I cannot leverage the Select API at all because the only thing I can give to `fetch_all` is a `MutexGuard`

Example:

```rs
pub struct DB {
    // Connection is mutable, so we must wrap it in a mutex to make sure there is concurrency issues
    pub connection: Mutex<SqliteConnection>,
}

impl DB {
    fn get_locked_connection(&mut self) -> MutexGuard<'_, SqliteConnection> {
        self.connection
            .lock()
            .expect("Count not get the lock on database")
    }

    /**
     * Get all the tracks (and their content) from the database
     */
    pub async fn get_all_tracks(&mut self) -> AnyResult<Vec<Track>> {
        let mut connection = self.get_locked_connection();

        let timer = TimeLogger::new("Retrieved and decoded tracks".into());
        let tracks = Track::select().fetch_all(&connection).await?; // error here
        timer.complete();
        Ok(tracks)
    }
}
```

The code would produce the following error:

```
error[E0277]: the trait bound `&MutexGuard<'_, SqliteConnection>: Executor<'_>` is not satisfied
  --> src/plugins/database.rs:63:22
   |
63 |         let tracks = Track::select().fetch_all(&connection).await?;
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Executor<'_>` is not implemented for `&MutexGuard<'_, SqliteConnection>`
   |
   = help: the following other types implement trait `Executor<'c>`:
             <&'c mut SqliteConnection as Executor<'c>>
             <&'c mut sqlx_core::any::connection::AnyConnection as Executor<'c>>
             <&Pool<DB> as Executor<'p>>
note: required by a bound in `SelectQueryBuilder::<'args, DB, M>::fetch_all`
  --> /Users/martpie/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ormlite-core-0.22.2/src/query_builder/select.rs:60:12
   |
58 |     pub async fn fetch_all<'executor, E>(self, db: E) -> Result<Vec<M>>
   |                  --------- required by a bound in this associated function
59 |     where
60 |         E: Executor<'executor, Database = DB>,
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `SelectQueryBuilder::<'args, DB, M>::fetch_all`
```

Do you have any idea how I can re-conciliate a `MutexGuard<SqliteConnection>` with what `ormlite` expects?

Have you faced this issue in highly asynchronous environment? Do you have maybe an alternative solution than Mutex to point me to?

Thank you again!

**Comment by kurtbuilds** [comment]
Do you know how to get the code working with plain `sqlx`? The types `ormlite` expects should be identical to the various parameters in `sqlx`.

You likely need to DerefMut the MutexGuard to get a `&mut SqliteConnection`. You can do it explicilty with `.deref_mut()`, or using operators with something like `&mut *connection_as_mutext_guard`.

**Comment by martpie** [comment]
Thank you, I finally found a solution to passing my MutexGuard around by using async Mutex + lifeguards, if anyone else is interested, here's a quick solution:

```rs
use tokio::sync::{Mutex, MutexGuard};

pub struct DBState(Mutex<DB>);

impl DBState {
    async fn get_lock(&self) -> MutexGuard<'_, DB> {
        self.0.lock().await
    }
}

pub struct DB {
    pub connection: SqliteConnection,
}

#[tauri::command]
async fn set_playlist_tracks(
    db_state: State<'_, DBState>,
    id: String,
    tracks: Vec<String>,
) -> AnyResult<Playlist> {
    db_state
        .get_lock()
        .await
        .connection // to stuff with connection
}
```

**Comment by kurtbuilds** [comment]
Glad you found a solution.

I haven't encountered this in a while (I think I have muscle memory now), but I remember when starting out with sqlx I sometimes encountered errors similar to the one you reported frequently, so thank you for sharing the code example you used to fix this.
