### ISSUE TITLE
Add ormlite to the Diesel benchmark

### ISSUE THREAD

**Issue by weiznich** [kurtbuilds/ormlite#9]
I would like to invent you to add ormlite to the relational database connection crates benchmark suite located inside of the [diesel repository](https://github.com/diesel-rs/diesel/tree/master/diesel_bench). These benchmarks are run regularly and results are published [here.](https://github.com/diesel-rs/metrics/) This would give potential users a good overview over the current state + you would also have a comparison with other crates for free.

**Comment by kurtbuilds** [comment]
Thanks for your comment here and on Reddit.

Unfortunately I have limited bandwidth, and I need to prioritize features over benchmarking.

Right now, I encourage end users to make a decision on ormlite based on usability, not performance. That said, `ormlite` is a thin layer on top of `sqlx`, so I reasonably believe performance will be close, if not within noise, compared to `sqlx`.

@weiznich If you'd like to add benchmarks, I'd appreciate it.

**Comment by kurtbuilds** [comment]
I'm going to close this for now.
